using System;
using FrontDesk.Core.Aggregates;
using PluralsightDdd.SharedKernel;
using Xunit;

namespace UnitTests.Core.AggregatesEntities.AppointmentTests
{
  public class Appointment_Constructor
  {
    [Fact]
    public void ConstructorCreatedAndIdAutoGenerated()
    {
      var scheduleId = Guid.NewGuid();
      var startTime = new DateTime(2021, 01, 01, 10, 00, 00);
      var endTime = startTime.AddHours(3);
      var range = new DateTimeRange(startTime, endTime);
      var appointment = new Appointment(1, scheduleId, 2, 3, 4, 5, range, "Title Test");

      Assert.Null(appointment.DateTimeConfirmed);
      Assert.Equal(1, appointment.AppointmentTypeId);
      Assert.Equal(scheduleId, appointment.ScheduleId);
      Assert.Equal(2, appointment.ClientId);
      Assert.Equal(3, appointment.DoctorId);
      Assert.Equal(4, appointment.PatientId);
      Assert.Equal(5, appointment.RoomId);
      Assert.Equal(3*60, appointment.TimeRange.DurationInMinutes());
      Assert.Equal("Title Test", appointment.Title);
      Assert.NotEqual(Guid.Empty, appointment.Id);
    }

    [Fact]
    public void ConstructorCreatedWithId()
    {
      var appointmentId = Guid.NewGuid();
      var appointment = new Appointment(appointmentId);

      Assert.Equal(appointmentId, appointment.Id);
    }
  }
}
