using System;
using FrontDesk.Core.Aggregates;
using PluralsightDdd.SharedKernel;
using Xunit;

namespace UnitTests.Core.AggregatesEntities.AppointmentTests
{
  public class Appointment_Constructor
  {
    [Fact]
    public void ConstructorCreatedAndIdAutoGenerated()
    {
      var scheduleId = Guid.NewGuid();
      var range = new DateTimeRange(DateTime.Now, DateTime.Now.AddHours(3));
      var appointment = new Appointment(1, scheduleId, 1, 1, 1, 1, range, "Title Test");

      Assert.Null(appointment.DateTimeConfirmed);
      Assert.Equal(1, appointment.AppointmentTypeId);
      Assert.Equal(scheduleId, appointment.ScheduleId);
      Assert.Equal(1, appointment.ClientId);
      Assert.Equal(1, appointment.DoctorId);
      Assert.Equal(1, appointment.PatientId);
      Assert.Equal(1, appointment.RoomId);
      Assert.Equal(3*60, appointment.TimeRange.DurationInMinutes());
      Assert.Equal("Title Test", appointment.Title);
    }

    [Fact]
    public void ConstructorCreatedWithId()
    {
      var appointmentId = Guid.NewGuid();
      var appointment = new Appointment(appointmentId);

      Assert.Equal(appointmentId, appointment.Id);
    }
  }
}
